import Head from 'next/head';
import styles from '../Layout/Layout.module.css';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Country Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>{children}</main>

        <footer className={styles.footer}>
          created by <a href='#'>leandrogtabak</a> - devChallenges.io
        </footer>
      </div>
    </>
  );
};

export default Layout;
